kilogram/urls.py
from django.urls import path
from . import views

app_name = 'kilogram'

urlpatterns=[
    path('',views.IndexView.as_view(), name = 'index'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from kilogram import views as kilogram_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',kilogram_views.IndexView.as_view(), name="root"),
    path('kilogram/',include('kilogram.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('logout/',auth_views.LogoutView.as_view(), {'next_page':'/'}, name='logout'),
    path('login',auth_views.LoginView.as_view(),{'templates_name':'kilogram/login.html'}),
    path('accounts/signup',kilogram_views.CreateUserView.as_view(), name='signup'),
    path('accounts/login/done',kilogram_views.RegisterView.as_view(), name='create_user_done'),
    path('accounts/list/', kilogram_views.simple_list, name='index1'),
]

kilogram/models.py
from django.db import models
import django_tables2 as tables
from .forms import *
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

# class SimpleTable(tables.Table):
#   class Meta:
#     model = User

# class UserIn(models.Model):
#   name = models.CharField(max_length=20)
#   user_id= models.CharField(max_length=30)
#   user_psw= models.


class Grade(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE)
    grade = models.IntegerField()
#
# class GroupB(models.Model):
#     user_b =models.ForeignKey(User, related_name='grouping_b',on_delete=models.CASCADE)
#     group_b = models.IntegerField()

# class ProfileTable(tables.Table):
#   class Meta:
#     model = GroupA
#
# class Related(tables.Table):
#   class Meta:
#     model = User
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#   if created:
#     Profile.objects.create(user=instance)
#
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#   instance.profile.save()

kilogram/forms.py
from django.contrib.auth.models import User,Group
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CreateUserForm(UserCreationForm): # 내장 회원가입 폼을 상속받아서 확장한다.
    email = forms.EmailField(required=True) # 이메일 필드 추가
    # grade = forms.IntegerField()
    # group = forms.ModelChoiceField(queryset = Group.objects.all(), required = True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    # def save(self, commit=True): # 저장하는 부분 오버라이딩
    #     user = super(CreateUserForm, self).save(commit=False) # 본인의 부모를 호출해서 저장하겠다.
    #     user.email = self.cleaned_data["email"]
    #     if commit:
    #         user.save()
    #     return user

    # def save1(self, commit=True):  # 저장하는 부분 오버라이딩
    #     user = super(CreateUserForm, self).save(commit=False)  # 본인의 부모를 호출해서 저장하겠다.
    #     user.grade = self.cleaned_data["grade"]
    #     if commit:
    #         user.save1()
    #     return user

kilogram/views.py
from django.shortcuts import render,render_to_response
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from .forms import *
from django.urls import reverse_lazy
from .models import *
from django.template import RequestContext

# Create your views here.

class IndexView(TemplateView):
    template_name='kilogram/index.html'

class CreateUserView(CreateView):
    template_name='registration/signup.html'
    form_class = CreateUserForm
    success_url = reverse_lazy('create_user_done')

class RegisterView(TemplateView):
    template_name = 'registration/signup_done.html'

def simple_list(request):
    queryset = User.objects.all()
    queryset1 = GroupA.objects.all()
    table = SimpleTable(queryset)
    table1 =ProfileTable(queryset1)

    getuser=User.models.get(id=1)
    userfiltered = User.objects.select_related()
    table2 = Related(userfiltered)

    context = {
        'table':table,
        'table1':table1,
        'table2': table2
    }
    return render(request, "kilogram/simple_list.html",context)

kilogram/templates/kilogram/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Kilogram</title>

  <!-- Bootstrap -->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'kilogram/style.css' %}" />

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'kilogram:index' %}"> <span class="glyphicon glyphicon-camera"> </span> Kilogram </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_active %}
          <li><a href="{%url 'login' %}"> <span class="glyphicon glyphicon-heart"></span> {{user.username}}</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{%url 'login' %}"> <span class="glyphicon glyphicon-user"></span> Login</a></li>
          <li><a href="{% url 'admin:index' %}">Admin</a></li>
          {% endif %}
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class="container">
    <div>
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

kilogram/templates/kilogram/index.html
{% extends 'kilogram/base.html' %}
{% block content %}

<h1>sssoso Main Page</h1>
    {% if user.is_authenticated %}
    Hi, {{ user.username }}
    <p><a herf="{% url 'logout' %}">logout<</a></p>
    {% else %}
    <p>You are not logged in</p>
    <a herf="{%  url 'login' %}">login</a>
    {% endif %}
{% endblock %}

kilogram/templates/kilogram/simple_list.html
{% extends 'kilogram/base.html' %}
{% block content %}

{% load django_tables2 %}
{% render_table table %}
{% render_table table1 %}
{% render_table table2 %}

{% endblock %}